from .checkpoints import ensure_checkpoint_dir, load_checkpoint, save_checkpoint
from .config import ConfigNode, load_config
from .bootstrap import (
    build_initial_classifier_from_linear_head,
    build_task0_ewc_terms,
    build_task0_replay_buffer,
    task0_baseline_payload,
)
from .data import (
    CIFAR10_CLASSES,
    CIFAR10TaskDataset,
    ContrastiveTaskDataset,
    LabelMapper,
    ReservoirReplayBuffer,
    SeqCIFAR10Builder,
    TaskConfig,
    TransformConfig,
    TwoCropTransform,
    build_transforms,
)
from .methods import train_co2l, train_er_ace, train_ewc, train_lwf, train_naive_finetuning
from .models import (
    ContinualClassifier,
    SupConLoss,
    SupConNetwork,
    AsymmetricSupConLoss,
    IRDLoss,
    build_cifar_resnet,
    build_cifar_resnet18,
)
from .train import (
    evaluate_class_il,
    evaluate_linear,
    evaluate_task_il,
    evaluate_taskwise_class_il,
    evaluate_taskwise_task_il,
    extract_features,
    get_confusion_matrix,
    set_seed,
    train_linear_head,
    train_supcon,
)
from .viz import (
    compute_average_over_past,
    compute_bwt_matrix,
    compute_final_transfer_metrics,
    compute_forgetting_matrix,
    plot_cl_metrics,
    plot_forgetting_metrics,
    plot_bwt_metrics,
    plot_forgetting_curves,
    plot_bwt_curves,
    plot_confusion_matrix,
    plot_embedding_snapshots,
    plot_embedding_snapshots_ind,
    plot_final_embeddings_comparison,
    plot_single_method_embeddings,
    plot_forgetting_by_task,
    plot_linear_history,
    plot_methods_comparison_class_il,
    plot_methods_comparison_task_il,
    plot_supcon_loss,
    plot_taskwise_heatmap,
)

__all__ = [
    # Config & checkpoints
    "ConfigNode",
    "load_config",
    "ensure_checkpoint_dir",
    "load_checkpoint",
    "save_checkpoint",
    # Bootstrap
    "build_task0_replay_buffer",
    "build_task0_ewc_terms",
    "build_initial_classifier_from_linear_head",
    "task0_baseline_payload",
    # Data
    "CIFAR10_CLASSES",
    "CIFAR10TaskDataset",
    "ContrastiveTaskDataset",
    "LabelMapper",
    "ReservoirReplayBuffer",
    "SeqCIFAR10Builder",
    "TaskConfig",
    "TransformConfig",
    "TwoCropTransform",
    "build_transforms",
    # Models & losses
    "ContinualClassifier",
    "SupConLoss",
    "SupConNetwork",
    "AsymmetricSupConLoss",
    "IRDLoss",
    "build_cifar_resnet",
    "build_cifar_resnet18",
    # Training & evaluation
    "evaluate_class_il",
    "evaluate_linear",
    "evaluate_task_il",
    "evaluate_taskwise_class_il",
    "evaluate_taskwise_task_il",
    "extract_features",
    "get_confusion_matrix",
    "set_seed",
    "train_linear_head",
    "train_supcon",
    # CL methods
    "train_co2l",
    "train_er_ace",
    "train_ewc",
    "train_lwf",
    "train_naive_finetuning",
    # Visualization
    "plot_supcon_loss",
    "plot_embedding_snapshots",
    "plot_embedding_snapshots_ind",
    "plot_linear_history",
    "plot_cl_metrics",
    "plot_forgetting_metrics",
    "plot_bwt_metrics",
    "plot_single_method_embeddings",
    "plot_methods_comparison_class_il",
    "plot_methods_comparison_task_il",
    "plot_forgetting_curves",
    "plot_forgetting_by_task",
    "plot_bwt_curves",
    "plot_taskwise_heatmap",
    "plot_final_embeddings_comparison",
    "plot_confusion_matrix",
    # Metrics
    "compute_forgetting_matrix",
    "compute_bwt_matrix",
    "compute_average_over_past",
    "compute_final_transfer_metrics",
]
